### ISSUE TITLE
The pre-trained pruned checkpoints doesn't contain any zero weight values

### ISSUE THREAD

**Issue by sarabjeetsingh007** [DeGirum/pruned-models#2]
Hey!
I was trying to use your pre-trained pruned checkpoints of ResNet50_Pruned_70, and parsed it to print out weight values (using model.layer1[1].conv2.weight). I noticed that there were no zero weight value, even though it is pruned. Can you help me understand why that is?

**Comment by shashichilappagari** [comment]
Hi, 
The pruned model does not necessarily prune all the layers. Even if all the layers are pruned, each layer can be pruned by a different factor. We have tried different pruning profiles to show performance trade-offs. Please take a look at https://github.com/DeGirum/pruned-models/blob/master/pruning_schedulers/resnet50_pruned_70_schedule.yaml to see the pruning profile. 
Let us know if you have further questions or need more help.

**Comment by sarabjeetsingh007** [comment]
Oh, I see. I just noticed that since the initial layer weights are very small, they are left unpruned. Thanks!
